import axios from 'axios';

/**
 * Fetches Billboard chart data.
 * - Development: calls Express API server at /api/chart (live scrape + YouTube API)
 * - Production: loads static /data/chart.json generated by prebuild.js at deploy time
 * @returns {Promise<Object>} Chart data with songs array
 */
export const fetchChart = async () => {
  try {
    const isDev = import.meta.env.DEV;
    const url = isDev ? '/api/chart' : '/data/chart.json';

    const response = await axios.get(url);
    const data = response.data;

    if (!data.success) {
      throw new Error(data.error || 'Failed to load chart data');
    }
    return data.data;
  } catch (error) {
    console.error('Failed to fetch chart:', error.message);
    throw error;
  }
};
